# Generated by Django 4.1.7 on 2023-03-11 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=12)),
                ('citizenship_no', models.CharField(max_length=10)),
                ('airport_name', models.CharField(choices=[('TIA', 'TIA'), ('DHANGADI', 'DHANGADI'), ('BHAIRAHAWA', 'BHAIRAHAWA'), ('PKR', 'PKR')], max_length=50)),
                ('destination_name', models.CharField(choices=[('TIA', 'TIA'), ('DHANGADI', 'DHANGADI'), ('BHAIRAHAWA', 'BHAIRAHAWA'), ('PKR', 'PKR')], max_length=50)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('THIRD', 'THIRD')], max_length=7)),
                ('citizenship_image', models.ImageField(blank=True, upload_to='citizenship')),
                ('vaccine_cert', models.FileField(blank=True, upload_to='vaccine_certificates')),
            ],
        ),
    ]
